project_id = "fpkjkqdfufhhicxkyqdw"

[functions.suggest-job-competencies]
verify_jwt = false

[functions.generate-job-description]
verify_jwt = false

[functions.legal-assistant]
verify_jwt = true

[functions.salary-assistant]
verify_jwt = true

[functions.incentive-assistant]
verify_jwt = true

[functions.create-employee-user]
verify_jwt = true

[functions.send-budget-report]
verify_jwt = true

[functions.check-agent-alerts]
verify_jwt = false

[functions.support-assistant]
verify_jwt = true
